name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: true
        default: 'v1.0.0'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsdl2-dev \
            libsdl2-image-dev \
            libchipmunk-dev \
            pkg-config
      
      - name: Build
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Package
        run: |
          mkdir -p platformer-linux
          cp build/platformer platformer-linux/
          cp -r assets platformer-linux/
          tar -czf platformer-linux-x64.tar.gz platformer-linux
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: platformer-linux-x64
          path: platformer-linux-x64.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          brew install cmake sdl2 sdl2_image chipmunk pkg-config
      
      - name: Build
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          
      - name: Package
        run: |
          mkdir -p platformer-macos
          cp build/platformer platformer-macos/
          cp -r assets platformer-macos/
          tar -czf platformer-macos-x64.tar.gz platformer-macos
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: platformer-macos-x64
          path: platformer-macos-x64.tar.gz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-pkg-config
      
      - name: Build
        run: |
          # Clone Chipmunk2D since it's not in the repository
          if [ ! -d "Chipmunk2D" ]; then
            git clone https://github.com/slembcke/Chipmunk2D.git
          fi
          # Use the working build script instead of CMake
          chmod +x build_msys2.sh
          ./build_msys2.sh
          
      - name: Package
        run: |
          mkdir -p platformer-windows
          cp physics_demo.exe platformer-windows/
          cp -r assets platformer-windows/
          # Copy required DLLs using ldd to find dependencies
          ldd physics_demo.exe | grep -i mingw | awk '{print $3}' | xargs -I{} cp {} platformer-windows/ || true
          # Also copy SDL2 and other DLLs that might not show up in ldd
          cp /mingw64/bin/SDL2.dll platformer-windows/ || true
          cp /mingw64/bin/SDL2_image.dll platformer-windows/ || true
          cp /mingw64/bin/libpng*.dll platformer-windows/ || true
          cp /mingw64/bin/zlib*.dll platformer-windows/ || true
          cp /mingw64/bin/libjpeg*.dll platformer-windows/ || true
          cp /mingw64/bin/libtiff*.dll platformer-windows/ || true
          cp /mingw64/bin/libwebp*.dll platformer-windows/ || true
          # Copy MinGW runtime libraries
          cp /mingw64/bin/libgcc_s_seh-1.dll platformer-windows/ || true
          cp /mingw64/bin/libstdc++-6.dll platformer-windows/ || true
          cp /mingw64/bin/libwinpthread-1.dll platformer-windows/ || true
          # List all DLLs in the package for debugging
          echo "DLLs included in package:"
          ls -la platformer-windows/*.dll || echo "No DLLs found"
          # Create zip archive using tar (available in MSYS2)
          tar -czf platformer-windows-x64.tar.gz platformer-windows
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: platformer-windows-x64
          path: platformer-windows-x64.tar.gz

  create-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Set release tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          name: C Platformer ${{ steps.set_tag.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            # C Platformer Release ${{ steps.set_tag.outputs.tag }}
            
            A physics-based 2D platformer demo built with SDL2 and Chipmunk2D.
            
            ## Features
            - Real-time physics simulation
            - Animated character sprites
            - Interactive box spawning
            - Debug visualization mode
            
            ## Controls
            - **A/←** - Move left
            - **D/→** - Move right  
            - **W/↑/Space** - Jump
            - **Left Click** - Spawn box
            - **F1** - Toggle debug mode
            
            ## Downloads
            Choose the appropriate package for your platform below.
            
            ### Installation
            1. Download and extract the archive for your platform
            2. Run the `platformer` executable
            3. Ensure the `assets` folder is in the same directory as the executable
            
          files: |
            artifacts/platformer-linux-x64/platformer-linux-x64.tar.gz
            artifacts/platformer-macos-x64/platformer-macos-x64.tar.gz
            artifacts/platformer-windows-x64/platformer-windows-x64.tar.gz